services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Sau\WP\Core\:
        resource: '../src/*'
        exclude: '../src/{Kernel.php,Twig/TwigEngine.php,Carbon/Carbon.php}'
    #Twig
    Sau\WP\Core\Twig\Twig:
        public: false
        arguments: ['@twig_engine']
    twig:
        alias: Sau\WP\Core\Twig\Twig
        public: true

    #Carbon
    Sau\WP\Core\Carbon\Carbon:
        public: false
        arguments: ['@service_container','@carbon_collector','@twig']
    carbon:
        alias: Sau\WP\Core\Carbon\Carbon
        public: true

    #Console
    Sau\WP\Core\Console\Console:
        arguments: ['@service_container','@carbon_collector']
