services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Sau\WP\Core\:
        resource: '../src/*'
        exclude: '../src/{Kernel.php,Twig/TwigEngine.php,Carbon/Carbon.php}'
    #Twig
    Sau\WP\Core\Twig\TwigEngine:
        public: false
        arguments: ['@service_container','@twig_collector']
    twig_engine:
        alias: Sau\WP\Core\Twig\TwigEngine

    Sau\WP\Core\Twig\Twig:
        public: false
        arguments: ['@twig_engine']
    twig:
        alias: Sau\WP\Core\Twig\Twig
        public: true

    #Console
    Sau\WP\Core\Console\Console:
        arguments: ['@service_container','@console_collector']
    console:
        alias: Sau\WP\Core\Console\Console
        public: true

    #WP
    Sau\WP\Core\WP\WP:
        arguments: ['@service_container','@wp_collector']
    wp:
        alias: Sau\WP\Core\WP\WP
        public: true

    #Carbon
    Sau\WP\Core\Carbon\Carbon:
        public: false
        arguments: ['@service_container','@carbon_collector','@twig']
    carbon:
        alias: Sau\WP\Core\Carbon\Carbon
        public: true
