services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: fals

    Sau\WP\Core\:
        resource: '../src/*'
        exclude: '../src/{Kernel.php,Twig/TwigEngine.php}'
